# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: db
#  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    whoami
    kubectl version
    helm version
    helmfile version
    ls -l
  displayName: 'Run a multi-line script'


- script: |
    cd helmfile && helmfile template --output-dir ./tmp
  displayName: 'Generate Helmfile template'


- script: |
    ls -l ./helmfile/tmp/helmfile-*-sonata/sonata/templates/
    echo " "
    echo " - - - "
    echo " "
    cat ./helmfile/tmp/helmfile-*-sonata/sonata/templates/*

  displayName: 'Test the template output'
